# docker-compose-biomero-client.yml - Simulates BIOMERO VM
version: "3"

services:
  biomeroworker:
    image: "cellularimagingcf/biomero:${NL_BIOMERO_VERSION:-latest}"
    hostname: biomeroworker-external
    environment:
      # Connect to external OMERO via host
      CONFIG_omero_master_host: "${EXTERNAL_OMERO_HOST}"
      CONFIG_omero_master_port: ${EXTERNAL_OMERO_PORT}
      OMERO_WORKER_NAME: biomeroworker-external
      CONFIG_omero_logging_level: 10
      CONFIG_omero_scripts_timeout: 604800000
      PERSISTENCE_MODULE: eventsourcing_sqlalchemy
      # Connect to external BIOMERO database via host
      SQLALCHEMY_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@${EXTERNAL_OMERO_HOST}:${BIOMERO_POSTGRES_HOST_PORT}/${BIOMERO_POSTGRES_DB}
      OMERO_USER: ${EXTERNAL_OMERO_USER:-root}
      OMERO_PASSWORD: ${EXTERNAL_OMERO_PASSWORD}
    ports:
      - "4062:4061"  # Expose ICE node port so OMERO server can reach it
    volumes:
      - "${HOST_OMERO_DATA_PATH}:/OMERO"  # Same host-mounted shared storage (simulates NFS)
      - "~/.ssh:/tmp/.ssh:ro"
      - "./web/slurm-config.ini:/opt/omero/server/slurm-config.ini:rw"
      - "${HOST_L_DRIVE_PATH}:/data"
      - "./biomeroworker/99-run-external.sh:/startup/99-run.sh:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - biomero-vm
    restart: unless-stopped

  omeroweb:
    image: "cellularimagingcf/omeroweb:${NL_BIOMERO_VERSION:-latest}"
    environment:
      # Connect to external OMERO via host
      OMEROHOST: ${EXTERNAL_OMERO_HOST}
      OMEROPORT: ${EXTERNAL_OMERO_PORT}
      CONFIG_omero_web_login__logo: "https://cembo.eu/wp-content/uploads/2021/04/Amsterdam-UMC.png"
      CONFIG_omero_scripts_timeout: 604800000
      ENV: TEST
      METABASE_SITE_URL: ${METABASE_SITE_URL}
      METABASE_SECRET_KEY: ${METABASE_SECRET_KEY}
      METABASE_IMPORTS_DB_PAGE_DASHBOARD_ID: ${METABASE_IMPORTS_DB_PAGE_DASHBOARD_ID}
      METABASE_WORKFLOWS_DB_PAGE_DASHBOARD_ID: ${METABASE_WORKFLOWS_DB_PAGE_DASHBOARD_ID}
      # Connect to external BIOMERO database via host
      INGEST_TRACKING_DB_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@${EXTERNAL_OMERO_HOST}:${BIOMERO_POSTGRES_HOST_PORT}/${BIOMERO_POSTGRES_DB}
      IMPORT_MOUNT_PATH: /data
      FORMS_MASTER_USER: ${FORMS_MASTER_USER}
      FORMS_MASTER_PASSWORD: ${FORMS_MASTER_PASSWORD}
      ROOTPASS: ${EXTERNAL_OMERO_PASSWORD}
    ports:
      - "${BIOMERO_WEB_HOST_PORT}:4080"  # Expose on different port
    volumes:
      - "./web/slurm-config.ini:/opt/omero/web/OMERO.web/var/slurm-config.ini:rw"
      - "${HOST_L_DRIVE_PATH}:/data:rw"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - biomero-vm
    restart: unless-stopped

  metabase:
    image: metabase/metabase@sha256:f7b5dc52c21aaa2dca910a450e7e6119a975090ce9fc80726aa0742882ca176c
    container_name: metabase-biomero
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_USER: ${METABASE_USER}
      MB_PASSWORD: ${METABASE_PASSWORD}
    ports:
      - "${METABASE_HOST_PORT}:3000"  # Expose on different port
    volumes:
      - "./metabase-biomero:/metabase-data"  # Host-mounted for persistence
    networks:
      - biomero-vm
    restart: unless-stopped

networks:
  biomero-vm:
    name: biomero-client-network
    driver: bridge