# This docker-compose file is configured to work with restored data volumes
# Use this after running the restore scripts from backup_and_restore/

version: "3"

services:
  # Name of our database, referenced in omero_db_host
  database:
    image: "postgres:16"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - omero
    volumes:
      # Uses external volume pointing to restored database
      - "database:/var/lib/postgresql/data"

  database-biomero:
    image: "postgres:16"
    environment:
      POSTGRES_USER: ${BIOMERO_POSTGRES_USER}
      POSTGRES_DB: ${BIOMERO_POSTGRES_DB}
      POSTGRES_PASSWORD: ${BIOMERO_POSTGRES_PASSWORD}
    networks:
      - omero
    volumes:
      # Uses external volume pointing to restored BIOMERO database
      - "database-biomero:/var/lib/postgresql/data"

  # Name of our omero server, referenced in omero_master_host
  omeroserver:
    image: "cellularimagingcf/omeroserver:${NL_BIOMERO_VERSION:-latest}"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: ${POSTGRES_USER}
      CONFIG_omero_db_pass: ${POSTGRES_PASSWORD}
      CONFIG_omero_db_name: ${POSTGRES_DB}
      CONFIG_omero_server_nodedescriptors: >-
        master:Blitz-0
        omeroworker-1:Tables-0,Indexer-0,PixelData-0,DropBox,MonitorServer,FileServer,Storm
        biomeroworker:Processor-0
      CONFIG_omero_master_host: omeroserver
      CONFIG_omero_scripts_timeout: 604800000
      ROOTPASS: ${OMERO_ROOT_PASSWORD}
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      # Uses external volume pointing to restored OMERO server data
      - "omero:/OMERO"
      - "../web/L-Drive:/data"

  omeroworker-1:
    image: "cellularimagingcf/omeroworker:${NL_BIOMERO_VERSION:-latest}"
    environment:
      CONFIG_omero_master_host: omeroserver
      OMERO_WORKER_NAME: omeroworker-1
      CONFIG_omero_scripts_timeout: 604800000
    networks:
      - omero
    volumes:
      - "omero:/OMERO"
      - "../web/L-Drive:/data"

  biomeroworker:
    image: "cellularimagingcf/biomero:${NL_BIOMERO_VERSION:-latest}"
    environment:
      CONFIG_omero_master_host: omeroserver
      OMERO_WORKER_NAME: biomeroworker
      CONFIG_omero_logging_level: 10
      CONFIG_omero_scripts_timeout: 604800000
      PERSISTENCE_MODULE: eventsourcing_sqlalchemy
      SQLALCHEMY_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@database-biomero:5432/${BIOMERO_POSTGRES_DB}
    networks:
      - omero
    volumes:
      - "omero:/OMERO"
      - "~/.ssh:/tmp/.ssh:ro"
      - "../web/slurm-config.ini:/opt/omero/server/slurm-config.ini:rw"
      - "../web/L-Drive:/data"

  omeroweb:
    image: "cellularimagingcf/omeroweb:${NL_BIOMERO_VERSION:-latest}"
    environment:
      OMEROHOST: omeroserver
      ROOTPASS: ${OMERO_ROOT_PASSWORD}
      CONFIG_omero_web_login__logo: "https://cembo.eu/wp-content/uploads/2021/04/Amsterdam-UMC.png"
      CONFIG_omero_scripts_timeout: 604800000
      ENV: TEST
      METABASE_SITE_URL: ${METABASE_SITE_URL}
      METABASE_SECRET_KEY: ${METABASE_SECRET_KEY}
      METABASE_IMPORTS_DB_PAGE_DASHBOARD_ID: ${METABASE_IMPORTS_DB_PAGE_DASHBOARD_ID}
      METABASE_WORKFLOWS_DB_PAGE_DASHBOARD_ID: ${METABASE_WORKFLOWS_DB_PAGE_DASHBOARD_ID}
      INGEST_TRACKING_DB_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@database-biomero:5432/${BIOMERO_POSTGRES_DB}
      IMPORT_MOUNT_PATH: /data
      FORMS_MASTER_USER: ${FORMS_MASTER_USER}
      FORMS_MASTER_PASSWORD: ${FORMS_MASTER_PASSWORD}
      ADI_ENABLED: ${ADI_ENABLED}
    networks:
      - omero
    ports:
      - "4080:4080"
    volumes:
      - "../web/slurm-config.ini:/opt/omero/web/OMERO.web/var/slurm-config.ini:rw"
      - "../web/L-Drive:/data:rw"

  metabase:
    image: metabase/metabase@sha256:f7b5dc52c21aaa2dca910a450e7e6119a975090ce9fc80726aa0742882ca176c
    container_name: metabase
    hostname: metabase
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_USER: ${METABASE_USER}
      MB_PASSWORD: ${METABASE_PASSWORD}
    networks:
      - omero
    ports:
      - "3000:3000"
    volumes:
      - "metabase:/metabase-data"

  omeroadi:
    image: "cellularimagingcf/omeroadi:${OMEROADI_VERSION:-latest}"
    privileged: true
    profiles:
      - "adi_enabled"
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "label=disable"
    environment:
      OMERO_HOST: omeroserver
      OMERO_USER: root
      OMERO_PASSWORD: ${OMERO_ROOT_PASSWORD}
      OMERO_PORT: 4064
      INGEST_TRACKING_DB_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@database-biomero:5432/${BIOMERO_POSTGRES_DB}
    networks:
      - omero
    volumes:
      - "omero:/OMERO"
      - "../web/L-Drive:/data"
      - "../config/omeroadi/groups_list.json:/auto-importer/config/groups_list.json"
    user: "1000:1000"

networks:
  omero:

# Define volumes with external references to the restored data
volumes:
  database:
    external: true
    name: omero-database-restored  # Update this name to match your restored volume
  database-biomero:
    external: true
    name: biomero-database-restored  # Update this name to match your restored volume
  omero:
    external: true
    name: omero-server-restored  # Update this name to match your restored volume
  metabase:
    external: true
    name: metabase-restored  # Update this name to match your restored volume
