name: Docker Image CI
on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: get the user or organization name
      run: echo "USER_NAME=$(echo '${{ github.repository }}' | awk '{print tolower($0)}' | cut -d/ -f 1  | tr -d -)" >> $GITHUB_ENV
      shell: bash
    - name: get the repository name
      run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk '{print tolower($0)}' | cut -d/ -f 2)" >> $GITHUB_ENV
      shell: bash  
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build and tag WEB
      run: docker build . --file ./web/Dockerfile --tag  ${{ env.USER_NAME }}/omeroweb:${{ steps.vars.outputs.tag }}
    - name: Push the tagged WEB Docker image
      run: docker push ${{ env.USER_NAME }}/omeroweb:${{ steps.vars.outputs.tag }}
    - name: Build and tag SERVER
      run: docker build . --file ./server/Dockerfile --tag  ${{ env.USER_NAME }}/omeroserver:${{ steps.vars.outputs.tag }}
    - name: Push the tagged SERVER Docker image
      run: docker push ${{ env.USER_NAME }}/omeroserver:${{ steps.vars.outputs.tag }}
    - name: Build and tag PROCESSOR
      run: docker build . --file ./worker-processor/Dockerfile --tag  ${{ env.USER_NAME }}/omeroworker-processor:${{ steps.vars.outputs.tag }}
    - name: Push the tagged PROCESSOR Docker image
      run: docker push ${{ env.USER_NAME }}/omeroworker-processor:${{ steps.vars.outputs.tag }}
    - name: Build and tag BASIC WORKER
      run: docker build . --file ./worker/Dockerfile --tag  ${{ env.USER_NAME }}/omeroworker:${{ steps.vars.outputs.tag }}
    - name: Push the tagged BASIC WORKER Docker image
      run: docker push ${{ env.USER_NAME }}/omeroworker:${{ steps.vars.outputs.tag }}

