name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - id: deployment
      name: Build Sphinx (classical)
      uses: sphinx-notes/pages@v3
      with:
        publish: false
        documentation_path: './docs'
        requirements_path: './docs/requirements.txt'
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}